import uuid
from app.database.session import SessionLocal
from app.models.user import User
from app.models.document import DocumentFolder

def test():
    db = SessionLocal()
    try:
        # Get first user
        user = db.query(User).first()
        if not user:
            print("No user found in DB! Please create a user or register first.")
            return
            
        print(f"Found user: {user.name} ({user.email}) - {user.id}")
        
        # Try to create a document folder
        folder = DocumentFolder(user_id=user.id, name="Test Folder Autogenerated")
        db.add(folder)
        db.commit()
        db.refresh(folder)
        print(f"Successfully created folder: {folder.name} with ID {folder.id}")
        
        # Clean up
        db.delete(folder)
        db.commit()
        print("Cleaned up folder.")
    except Exception as e:
        print("ERROR:", e)
    finally:
        db.close()

if __name__ == "__main__":
    test()
